name: Docker

env:
  BASENAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  REGISTRY: hub.docker.com
  IMAGE_TAG: latest

on:
  pull_request:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  push:
    branches: [ "main", "master", "prod*" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: .
        dockerfile: Dockerfile
        name: ${{ env.BASENAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64
        snapshot: true
        tags: ${{ env.IMAGE_TAG }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
